### ISSUE TITLE
How to pause timeRemaining?

### ISSUE THREAD

**Issue by TechWeekSomewhere** [Figure53/QDisplay#5]
Hello,

I am looking for a way to pause the timeRemaining in the QDisplay window. Is this possible with a simple command in a script cue? I've tried the obvious guess such as "set timeRemaining to pause" which didn't work.

Thanks!

**Comment by ChrisAshworth** [comment]
Hi there @TechWeekSomewhere , thanks for your question!

There is not currently a way to pause the time remaining; once set it will always count down to zero.

**Comment by ChrisAshworth** [comment]
However @TechWeekSomewhere if you are using QLab and email us at support@figure53.com with what you are trying to do, we might be able to help some other way!

**Comment by TechWeekSomewhere** [comment]
Hi @ChrisAshworth thanks for clearing that up! I think I found another solution, but will be sure to send support an email. Thanks again!
